jscomps/EmbedLiteJSComponents.manifest, jscomps/IntentProtocolHandler.js, jscomps/Makefile.am
=> [embedlite-components] Intent protocol handler. Fixes JB#50750 OMP#JOLLA-164

jsscripts/FormAssistant.js, jsscripts/Makefile.am, jsscripts/embedhelper.js
**Moved from [gitlab](https://git.sailfishos.org/mer-core/embedlite-components/merge_requests/132).**
Advertised to the UI to present to the user.
=> Advertise saved logins for login form

jsscripts/embedhelper.js
This does not yet make link handling working as "Gesture:SingleTap" is not yet working.
=> Fix errors from touch start and end

jscomps/PromptService.js, jscomps/nsLoginManagerPrompter.js, jsscripts/Prompt.jsm
Rebased @llewelld 's changes from https://github.com/sailfishos/embedlite-components/pull/5
=> Pass translation key for login and auth prompts

jscomps/EmbedLiteFaviconService.js, jsscripts/SelectionHandler.js, jsscripts/Util.js, jsscripts/embedhelper.js
See gecko-dev/dom/webidl/Window.webidl
https://github.com/sailfishos/embedlite-components/pull/20
=> [embedlite-components] Adapt window.queryInterface usage (part 2). Fixes JB#55335 OMP#JOLLA-330

jscomps/EmbedLiteChromeManager.js, jsscripts/NetErrorHelper.jsm
See https://bugzilla.mozilla.org/show_bug.cgi?id=1460735
https://github.com/mozilla/gecko-dev/commit/3b8785a733ca38059a8402eec0c1b379d4eea538
=> [embedlite-components] Remove nsIDOMDocument usage. Fixes JB#55334 OMP#JOLLA-329

jsscripts/embedhelper.js
See https://github.com/sailfishos-mirror/gecko-dev/commit/8fdbb6d26b5ba5a492e2c4cdddb0b52e319ac542
=> [embedlite-components] Adapt Services.locale.setAvailableLocales to new API. Fixes JB#55330 OMP#JOLLA-336

jsscripts/FormAssistant.js, jsscripts/SelectAsyncHelper.js, jsscripts/SelectionHandler.js, jsscripts/embedhelper.js
Fix rest of addEventListener errors. This PR also fixes Ci.nsIDOMHTMLInputElement not being defined error.
=> Fix addEventListener part two

jsscripts/embedhelper.js
Reverts sailfishos/embedlite-components#32
=> Revert "Use PurgeHistory from legacy history"

jscomps/EmbedLiteErrorPageHandler.js, jscomps/FilePicker.js, jscomps/PromptService.js, jscomps/nsLoginManagerPrompter.js, jsscripts/embedhelper.js
This PR contains three commits
1) Fix PrivateBrowsingUtils reference errors
2) Comment out LoginManagerContent call
3) Fix "QueryInterface is not a function" error
Alert, confirm, prompt works now. This turned out to be smaller change than expected.
=> Adapt PromptService

.gitmodules, jscomps/EmbedLiteSearchEngine.js
Needs also https://github.com/sailfishos/embedlite-components-search-engines/tree/sailfishos-esr78
=> [embedlite-components-search-engines] Search engine init fix for esr78. Fixes JB#55267 OMP#JOLLA-304

jscomps/EmbedLiteGlobalHelper.js, jsscripts/FormAssistant.js, jsscripts/embedhelper.js
See: https://github.com/sailfishos-mirror/gecko-dev/commit/
7cbc074da1804cb7f6a5d938fbf6d16eba611017
=> [embedlite-components] Rename LoginManagerContent to LoginManagerChild. Contributes to JB#55434 OMP#JOLLA-342

jscomps/HelperAppDialog.js
This ended up being simpler than anticipated. Didn't immediately spot those errors coming undefined FileUtils and friends.
=> [embedlite-components] Adapt HelperAppDialog aka file saving to work. Fixes JB#55499 OMP#JOLLA-384

jsscripts/embedhelper.js
This adds event listener to the childprocessmessagemanager when sharedData
changes.
ActorManagerChild throws an exception when "ChildSingletonActors"
is not yet available in the sharedData.
@adenexter this kind of a fallback sorts this out. What do you think? Surely, a bit on a hack side but better this way so that we do fail on the ActorManagerChild::init.
=> [embedlite-components] Add fallback attaching for ActorManagerChild. JB#55890 OMP#JOLLA-437

jsscripts/SelectionPrototype.js
This fixes undefined references when trying to select text.
=> [embedlite-components] Remove reference to nsIDOMNode as it no longer exists. JB#56066 OMP#JOLLA-479

jscomps/EmbedLiteConsoleListener.js
This updates the logging triggered by "console-api-log-event" so that the passed objects are unbundled and displayed correctly.
Most of the new code has been taken from GeckoViewConsole.jsm, here:
https://github.com/sailfishos-mirror/gecko-dev/blob/2834d64c4b16c7b93857fd58ca55dc76d8176bfd/mobile/android/modules/geckoview/GeckoViewConsole.jsm#L55
As before `EMBED_CONSOLE="stacktrace"` must be set in the environment in order to activate this logging.
=> Fix javascript console logging output. JB#55880 OMP#JOLLA-435

jscomps/EmbedLiteWebrtcUI.js
The state of media devices is reported by the ObserverService:
message: webrtc-media-info
payload: {"audio":false,"video":false}
=> [embedlite-components] Broadcast media types used for WebRTC. JB#56332

jscomps/PrivateDataManager.js
Use a new API for clearing cookie and cache.
Replace clearing of "cookie" with "cookies-and-site-data"
=> Refactoring PrivateDataManager.js and add ability of removing site data

jsscripts/embedhelper.js
Passes double taps to javascript handlers.
=> Pass double taps to javascript handlers. JB#56765 OMP#JOLLA-607

jscomps/EmbedLiteChromeManager.js, jscomps/EmbedLiteConsoleListener.js, jscomps/EmbedLiteGlobalHelper.js, jscomps/EmbedLiteSearchEngine.js, jscomps/EmbedLiteWebrtcUI.js, jscomps/EmbedliteDownloadManager.js, jscomps/LoginManagerPrompter.js, jscomps/PromptService.js, jsscripts/embedhelper.js
Adds changes needed to support the updates to gecko for ESR 91.
=> [embedlite-components] Changes needed to support ESR 91

jscomps/LoginManagerPrompter.js, jscomps/PromptService.js
Fixes basic auth but still has some issues left.
Disablíng usual code path for now until certain issues are resolved, which causes autofill of fields to fail in certain situations.
=> Sync LoginManagerPrompt to upstream changes
