- jscomps/LoginsHelper.js
Adds "add" and "removeAll" actions to the "embedui:logins" notifications observed by LoginsHelper.
These actions are used by the unit tests.
> Add login actions needed for unit tests

- jsscripts/ClickEventBlocker.js
Any form actions the user triggers while in the captive portal will be handled inside the captive portal, rather than breaking out into the browser, independent of whether they are in the same origin as the page or not.
However, any future clicks will break out if they don't match the origin of the form page, rather than of any subsequent pages loaded.
There are two commits, the first demonstrates a simpler (but I think incorrect) method. If this combined changes are found to be a suitable approach I'd squash them before merging.
> [embedlite-components] Handle form actions inside the captive portal. JB#54920

- jscomps/EmbedLiteConsoleListener.js
- jscomps/EmbedLiteJSComponents.manifest
Any privileged components in embedlite-components that start up before
EmbedLiteConsoleListener aren't able to log. Since the start-up sequence
is alphabetical based on the component class name, this change ensures
the EmbedLiteConsoleListener is started before other components.
> Ensure EmbedLiteConsoleListener starts up first. JB#54970 OMP#JOLLA-270

- jscomps/EmbedliteDownloadManager.js
Remove uses of Task.jsm from EmbedliteDownloadManager.js as per
Mozilla Bug 1374282. See e.g. 66f6d259bc9ab9416f2de81fbcafe0b76c97bc5c
from gecko-dev tree.
> [embedlite-components] Remove usage of Task.jsm. Contributes to JB#55143

- embedlite-components.pro
- jscomps/UserAgentOverrideHelper.js
- jsscripts/Makefile.am
- jsscripts/UserAgentOverrides.jsm
- jsscripts/UserAgentUpdates.jsm
- link_to_system.sh
UserAgentOverrides.jsm was removed from gecko-dev
https://bugzilla.mozilla.org/show_bug.cgi?id=1513574
We still rely on this to allow per-uri UA overrides to be provided.
This commit moves the esr60 version of UserAgentOverrides.jsm
and UserAgentUpdates.jsm into embedlite-components, and then updates
them slightly to align with esr78 changes.
> [embedlite-components] Move UserAgentOverrides.jsm to embedlite-components. Contributes to JB#55142

- jscomps/EmbedLiteGlobalHelper.js
1) RemoteLogins:insecureLoginFormPresent no longer exist
2) RemoteLogins messages are now Pass PasswordManager
3) Read global message via Services.jsm
4) Add LoginManagerParent const variable
https://bugzilla.mozilla.org/show_bug.cgi?id=1531959
- Change all RemoteLogins message names to PasswordManager in pwmgr code
- https://github.com/sailfishos-mirror/gecko-dev/commit/1371a0545cdd9323b5a6fea14ad3a78658c9bace
https://bugzilla.mozilla.org/show_bug.cgi?id=1527828
- Remove insecure password field detection code for the address bar
- https://github.com/sailfishos-mirror/gecko-dev/commit/87888ef23587b953bd3045f745d74ab6c9d010eb
https://bugzilla.mozilla.org/show_bug.cgi?id=1567175
- support password manager in out of process iframes
- …
> [embedlite-components] Adapt LoginManagerParent listener registrations. Fixes JB#55144 OMP#JOLLA-276

- jsscripts/ContextMenuHandler.js
- jsscripts/FormAssistant.js
- jsscripts/SelectAsyncHelper.js
- jsscripts/SelectionHandler.js
- jsscripts/embedhelper.js
- First this reverts previous addEventListener fixes
- Fix Ci.nsIDOMMouseEvent references from context menu handling
- Fix windowUtils quering from context menu handler
- Load each embedhelper.js subscript to context this (content) : https://github.com/sailfishos-mirror/gecko-dev/blob/esr78/js/xpconnect/idl/mozIJSSubScriptLoader.idl#L32
- After above fix redeclaration of XPCOMUtils in FormAssistant
- For time being add sendAsyncMessage hack
- Fix Node.Element reference errors
> Components loading fixes

- overrides/netError.css
Tweaks the overridden gecko error page CSS to make the design better
integrate with the OS:
1. Removes the hatched bar from the top of the page.
2. Adds a yellow border around the page.
3. Removes the line between the header and body text.
4. Removes the rounded border and adds a line to the bottom of the text
entry box.
5. The "connecting wifi" animation is shown as moving dashes.
The changes apply to the neterror, certerror and blockedsite error
pages. Can be texted by visiting about:neterror and about:certerror.
> Update gecko error page design. JB#54832 OMP#JOLLA-224

- jsscripts/SelectionHandler.js
- jsscripts/SelectionPrototype.js
Touch coordinates are off when content zoomed in but that
error is covered by JB#55472 and JOLLA-365.
> [embedlite-components] Fix references errors from text selection. Fixes JB#55471 OMP#JOLLA-364

- jscomps/EmbedLiteJSComponents.manifest
- jscomps/LoginManagerPrompter.js
- jscomps/Makefile.am
- jscomps/PromptService.js
- jscomps/nsLoginManagerPrompter.js
- link_to_system.sh
Updates nsLoginManagerPrompter.js to use the updated `nsILoginManagerPrompter` interface of ESR78. The main change is that rather than passing the browser during init, it instead passes it each time a username/password is to be requested from the user.
The code has also been updated to better align with the gecko implementations of the interfaces which we're overriding.
> Update to new nsILoginManagerPrompter interface. JB#55760 OMP#JOLLA-418

- jscomps/ContentPermissionPrompt.js
When in private browsing mode, it shouldn't be possible to permanently record permissions, since this would leak location information.
This change passes the status of private browsing to the UI so that it can disable the option to save permission info when in private browsing mode.
> Pass private browsing status when requesting permissions. JB#55925 OMP#JOLLA-445

- jscomps/EmbedLiteSearchEngine.js
- jsscripts/SelectionPrototype.js
The `nsISearchService.currentEngine` parameter is no longer available in ESR78. However, we were using it to determine whether or not to display the search button in the text selection toolbar. Since it returned `undefined`, the button was always hidden.
As it happens we already use `nsISearchService.defaultEngine` to specify the search engine, so this changes the toolbar button to use this instead.
A second commit removes unused code from EmbedLiteSearchEngine.js. Portions of it were no longer valid after the update from `nsIBrowserSearchService` in ESR60 to `nsISearchService` in ESR78 anyway.
> Reinstate search in text selection toolbar. Fixes JB#56187 OMP#JOLLA-505

- jsscripts/embedhelper.js
Updates embedhelper.js to use the new `nsITypeAheadFind` interface, so that in-page search works again. The new interface is slightly cleaner, since the results are returned as the return values to the functions (rather than having to access an internal variable of Finder.js).
> Update to new nsITypeAheadFind interface. Fixes JB#56261 OMP#JOLLA-521

- jscomps/AboutRedirector.js
- jscomps/EmbedLiteErrorPageHandler.js
Fix AboutRedirector to use the up to date newChannel() function
signature and use Services.io.newChannelFromURIWithLoadInfo() instead of
newChannel() the call to which was failing because it required
additional arguments.
Then fix EmbedLiteErrorPageHandler to remove the use of the
nsIBadCertListener2 interface which no longer exists by porting the
changes from https://phabricator.services.mozilla.com/D21791.
> [embedlite-components] Fix TLS certificate error page. JB#56093 OMP#JOLLA-491

- jscomps/EmbedLiteWebrtcUI.js
The state of media devices is reported by the ObserverService:
message: webrtc-media-info
payload: {"audio":false,"video":false}
> [embedlite-components] Broadcast media types used for WebRTC. JB#56332

- jscomps/EmbedLiteConsoleListener.js
API change in esr78, see https://github.com/sailfishos-mirror/gecko-dev/blob/esr78/netwerk/base/nsIStreamListener.idl#L34-L38.
> [embedlite-components] Fix EmbedLiteConsoleListener. JB#56414 OMP#JOLLA-546

- jsscripts/FormAssistant.js
- jsscripts/embedhelper.js
Applies two fixes:-
The first fixes password autocomplete: when a username for a previously stored login is entered into a username field, the password field for that login will be filled out automatically.
The second fixes usernames offered in the keyboard AutoFill bar: when the caret is in an empty username field on a page for which a login is know, the username is offered as an option in the keyboard suggestions bar.
> Fix username and password autocomplete. Fixes JB#56496 OMP#JOLLA-561

- jsscripts/embedhelper.js
Check ownerDocument is not null before deferencing it along with the
other conditions which would cause LoginFormFactory.jsm to throw a
"createFromField requires a password or username field in a document"
error.
> [embedlite-components] Fix Form ownerDocument is undefined error. JB#56595 OMP#JOLLA-564

- jscomps/EmbedLiteGlobalHelper.js
Touch the recipeParentPromise lazy getter so we don't get
`this._recipeManager is undefined` errors during tests.
Inspered by browser/components/extensions/test/browser/head.js
> [embedlite-components] Touch the recipeParentPromise lazy getter. JB#56513 OMP#JOLLA-558

- jscomps/EmbedLiteGlobalHelper.js
- overrides/Makefile.am
- overrides/aboutCertError.xhtml
- overrides/en-US/aboutCertError.ftl
- overrides/en-US/brand.ftl
- overrides/fi/aboutCertError.ftl
- overrides/fi/brand.ftl
- overrides/netError.css
- overrides/ru/aboutCertError.ftl
- overrides/ru/brand.ftl
- tools/mine-localisation-files.py
The description of the error is no longer encoded in the about:certerror
URL and needs to be constructed in the page itself.
Also fix the caret icon so it's apparent when the collapsed headings have
been expanded as with neither that nor content it wasn't apparent when
clicking worked.
> [embedlite-components] Populate the technical details of the certificate page. JB#56370 OMP#JOLLA-541

- jscomps/LoginManagerPrompter.js
When user saves password for site part1.hostname.com, the password save dialog asks "Save password for 'hostname.com'?", showing only Top Level Domain instead of full domain. So user might think he saves password for all subdomains of hostname.com (like part2.hostname.com, subpart4.part3.hostname.com etc.). In order to inform user more accurately, we should show full domain in that dialog.
> [embedlite-components] Fixed password save dialog showing incorrect host. Fixes JB#57143

- jsscripts/SelectionHandler.js
When trying to copy to clipboard without selection following got triggered:
> JavaScript error: chrome://embedlite/content/SelectionHandler.js,
> line 310: TypeError: this._cache.selection is undefined
Fix: return early if no cache or selection.
On error case following got triggered:
> JavaScript error: chrome://embedlite/content/SelectionHandler.js,
> line 66: TypeError: aJson is undefined
Fix: have json argument in all this.sendAsync calls.
Signed-off-by: Raine Makelainen <raine.makelainen@jolla.com>
> [embedlite-components] Make selection handling more robust. Fixes JB#58662

- rpm/embedlite-components-qt5.spec
We redirect all git.sailfishos.org to github.com but it is better to have the correct url here to avoid confusion, when retrieving the URL with rpm, for instance.
> Change URL from git.sailfishos.org to github.com

- jscomps/EmbedLiteErrorPageHandler.js
Allows working around invalid certificate by temporary adding it - the method has one more param
> rememberValidityOverride additional param

- configure.ac
- jsscripts/embedhelper.js
- rpm/embedlite-components-qt5.spec
Beef:
Sailfish-browser startup triggers now search reset. While that could
be avoided, the code here is already considering empty search string
as request to finish the search if such was initialized.
Cleaned up the build and removed reference to ancient qt4 packaging while at it.
> Unnecessary finder
